
require_relative '../resource_group'

module Alcatel
  module CallProcessing
    class CPCALLMOUTPULSEMAP
 
      include Alcatel::ResourceGroup
 
      def self.dto
        @dto ||= resource('OUTPULSEMAP', fields) do
          include Resource::OUTPULSEMAP
        end
      end

      def self.fields
        %w[ OUTPULSEMAPID DIGITPATTERN INPUTNOA MINDIGITCOUNT MAXDIGITCOUNT
            OUTPULSEMAPINDEX1 CAUSEVALUE1 OUTPULSEMAPINDEX2 CAUSEVALUE2
            OUTPULSEMAPINDEX3 CAUSEVALUE3 OUTPULSEMAPINDEX4 CAUSEVALUE4
            OUTPULSEMAPINDEX5 CAUSEVALUE5 OUTPULSEMAPINDEX6 CAUSEVALUE6
            OUTPULSEMAPINDEX7 CAUSEVALUE7 OUTPULSEMAPINDEX8 CAUSEVALUE8
            OUTPULSEMAPINDEX9 CAUSEVALUE9 OUTPULSEMAPINDEX10 CAUSEVALUE10
            OUTPULSEMAPINDEX11 CAUSEVALUE11 OUTPULSEMAPINDEX12 CAUSEVALUE12
            OUTPULSEMAPINDEX13 CAUSEVALUE13 OUTPULSEMAPINDEX14 CAUSEVALUE14
            OUTPULSEMAPINDEX15 CAUSEVALUE15 OUTPULSEMAPINDEX16 CAUSEVALUE16
            OUTPULSEMAPINDEX17 CAUSEVALUE17 OUTPULSEMAPINDEX18 CAUSEVALUE18
            OUTPULSEMAPINDEX19 CAUSEVALUE19 OUTPULSEMAPINDEX20 CAUSEVALUE20
            OUTPULSEMAPINDEX21 CAUSEVALUE21 OUTPULSEMAPINDEX22 CAUSEVALUE22
            OUTPULSEMAPINDEX23 CAUSEVALUE23 OUTPULSEMAPINDEX24 CAUSEVALUE24
            OUTPULSEMAPINDEX25 CAUSEVALUE25 OUTPULSEMAPINDEX26 CAUSEVALUE26
            OUTPULSEMAPINDEX27 CAUSEVALUE27 OUTPULSEMAPINDEX28 CAUSEVALUE28
            OUTPULSEMAPINDEX29 CAUSEVALUE29 OUTPULSEMAPINDEX30 CAUSEVALUE30
            OUTPULSEMAPINDEX31 CAUSEVALUE31 OUTPULSEMAPINDEX32 CAUSEVALUE32
            LEADINGDIGITSCUT LEADINGDIGITSADD DESCRIPTION CPC NATUREOFADDRESS OLI CPC_PRIORITY
        ].map { |field_name| field_name.downcase.to_sym }
      end

      def initialize table
        @entries = table.map { |row| self.class.dto.new(*row) }.each(&:convert_fields)
      end

    end
  end
end
 
